 class Strings {

 String  PleaseWait;
  String appName;
  String langPage;
  String arabicLang;
  String englishLang;
  String languages;
  String languagesDes;
  String alertExitTitle;
  String exitApp;
  String home;
  String schedule;
  String profile;
  String product;
  String services;
  String serviceNoti;
  String servicesDetails;
  String selectServices;
  String contract;
  String notification;
  String news;
  String municipalCouncils;
  String theMedia;
  String about;
  String contactUs;
  String complaintsAndSuggestions;
  String logout;
  String login;
  String userName;
  String fillDataError;
  String errorUserName;
  String userPassword;
  String errorPassword;
  String signIn;
  String signInWithFacebook;
  String dontHaveAccount ;
  String register ;
  String alreadyHaveAccount ;
  String signUp;
  String loginGist;
  String firstUserName;
  String lastUserName;
  String phoneNum ;
  String massagesDesc ;
  String email ;
  String userRePassword;
  String forgetPassword;
  String passwordLess6;
  String errorMatchPassword;
  String errorPhone ;
  String phoneNumValid;
  String alertLogout;
  String exitapp;
  String emailUsed;
   String send;
   String FirstName;
   String share;
  String secondname;
   String photoAlbum;
  String videoAlbum;
  String MunicipalCouncils;
  String CurrentCouncils;
  String PreviousCouncils;
  String MunicipalMembers;
  String employees;
  String yes;
  String no;
  String ReadMore;
  String search;
  String enterusername;
  String enterpassword;
   String userEmail;
  String welcome;
  String title;
  String ComplaintTitle;
  String yourMsg;
  String yourProblem;
  String yourNote;
  String addAppointment;
  String uploadImage;
  String location;
  String locationClient;
  String Appointment;
  String ClientNotes;
  String empEvaluation;
  String rate;
  String empName;
  String sendNote;
  String AdminNotes;
  String WriteYourNotes;
  String Contract;
  String Landscaping;
  String Cost;
  String Warranty;
  String Traps;
  String Report;
  String Location;
  String ReceiptVoucher;
  String Invoice;
  String OfficerNotes;
  String WriteNotes;
  String SendNotes;
  String Profile;
  String Settings;
  String EditProfile;
  String ChangePassword;
  String Notification;
  String Language;
  String ChangeUserName;
  String ChangePhoneNumber;
  String ChangeLocation ;
  String Cancel ;
  String Note ;
  String Change ;
  String OldPassword;
  String NewPassword;
  String ConfirmNewPassword ;
  String notificationOffS ;
  String NotificationON ;
  String NotificationOff ;
  String changeDataSuccess;
  String changeImageSuccess;
  String ok;
  String alerterror;
  String alertWrongChange;
  String Passwordliss6;
  String filterBy;
  String complete;
  String workingOn;
  String cancel;
  String status;
  String problem;
  String Products;
  String Product;
  String ExchangePoint;
  String points;
  String JD;
  String ProductPrice;
  String Quantity;
 String terms;
 String sendDone;
 String wrongEmailOrPassword;
 String accNotActive;
 String outOfTime;
 String pleaseEnterYourName;
 String FAQ;
 String partner;

 String checkYourEmail;
 String sendPassword;
String sendProduct;
String sendProductinfo;
String alertDoneChange;
String selectProduct;
String SearchByDate;
String EmployeePage;
String ClientWindow;
String sendNoteSuccessfully;
String sendAppointment;
String menu;
String viewServices;
String details;
String NoServices;
String blogs;
String subscribeService;
String Changelanguage;
String Comments;
String LeaveComment;
String EnteryourName;
String EnteryourEmail;
String writComment;
String note;
String Success;
String NoComment;
String Welcometo;
String PrivacyPolicy;
String CommentedSuccessfully;
String Waitingadminapproval;
String enterFullName;
 String enterYourEmail;
 String forgotYourPassword;
 String createANewAccount;
 String registration;
 String pleaseEnterRealName;
 String pleaseFilltheData;
 String pleaseEnterYourEmail;
 String enterValedEmail;
 String ClientAccountcreated;
 String ChooseLocation;
 String ChooseyourLocation;
 String ForgotPassword;
 String FillEmail;
 String EmailInvalid;
 String PleaseCheckPassword;
 String noteLogin;
 String LoginCommented;
 String offers;
 String IndestryType;
 String Instegram;
 String Address;
 String Twitter;
 String ourclients;
 String companyName;
 String Facebook;
 String SnapChat;
 String Submittedsuccessfully;
 String assoon;

}

class EnglishString extends Strings {


  EnglishString() {
    ClientAccountcreated='Your account has been successfully created as a customer';
    ForgotPassword = 'Write your e-mail and we will send to you the password';
    FillEmail = 'Write your Email';
    EmailInvalid = 'Email Invalid';
    assoon = 'we will contact with you as soon as possible';
    PleaseCheckPassword='Please Check Password';
    ChangePassword='Change Password';
    ChooseyourLocation='Choose your Location';
    enterYourEmail='Enter Your Email';
    forgotYourPassword='Forgot your password?';
    pleaseEnterYourName='Please Enter Your Name';
    pleaseFilltheData='please Fill the Data';
    pleaseEnterYourEmail='Please Enter Real Email';
    registration='Registration';
    loginGist='login as Gist';
    createANewAccount='Create A New Account?';
    langPage = 'Language';
    arabicLang = 'العربية';
    englishLang = 'English';
    subscribeService = 'subscribe Service';
    languages = 'عربي';
    Facebook = 'Facebook url';
    languagesDes = 'Language';
    alertExitTitle='Alert Exit';
    exitApp='Do you want to exit an App ';
    home='Home';
    Submittedsuccessfully='Submitted successfully';
    ourclients='our clients';
    FAQ='FAQ';
    SnapChat='SnapChat url';
    schedule='Schedule';
    profile='Profile';
    partner='Partner';
    product='Products';
    services='Services';
    serviceNoti='Service:';
    selectServices='Select Services';
    servicesDetails='Service Details';
    contract='Contract';
    notification='Notification';
    news='News';
    Note='Note';
    offers='Offers';
    Address='Address';
    municipalCouncils='Municipal Councils';
    theMedia='The Media';
    about='About Us';
    contactUs='Contact Us';
    complaintsAndSuggestions='Complaints And Suggestions';
     logout='Logout';
     login='Login';
    userName='User Name';
    fillDataError = 'Please Fill your Data';
    errorUserName='User name can\'t be empty';
    userPassword='Password';
    errorPassword = 'Password can\'t be empty';
    signIn = 'SignIn';
    signInWithFacebook = 'sign In With Facebook';
    dontHaveAccount = 'Don\'t Have a Account ?';
    register = 'Register';
    alreadyHaveAccount = 'Already Have an Account ?';
    signUp = 'SignUp';
    firstUserName = 'First Name';
    lastUserName = 'Last Name';
    phoneNum='Phone Number ';
    massagesDesc='Messages ';
    email='Email';
    userRePassword = 'Retype Password';
    forgetPassword = 'Forgot Password ? ';
    passwordLess6 ='Must more 6 character';
    errorMatchPassword = 'Password must Match !';
    errorPhone='Phone Number can\'t be empty ';
    phoneNumValid='mobile number must be valid';
    alertLogout='Alert Logout';
    exitapp='Do you want to logout an App ';
    emailUsed='email already used';
    send='Send';
      FirstName = 'First Name';
    secondname = 'Second Name';
     photoAlbum = 'Photo Album';
    videoAlbum = 'Video Album';
    MunicipalCouncils = 'Municipal Councils';
    CurrentCouncils = 'Current Councils';
    PreviousCouncils = 'Previous Councils';
    MunicipalMembers = 'Municipal Members';
    employees = 'Employees';
    share = 'share App';
    yes = 'Yes';
    no = 'No';
    ReadMore = 'Read More';
    search = 'Search';
    enterusername = 'Please Enter Email or Phone Number  ';
    enterpassword = 'Please Enter Password';
     welcome = 'Welcome to Al-Hudhud';
     yourMsg = 'Your Message';
    title = 'Title';
    ComplaintTitle = 'If You Have Any Suggestion Or Complaints,Lets Us Know .';
    userEmail = 'Email';
    PleaseWait='Please Wait';
    addAppointment='Add Appointment';
    location='Location';
    locationClient='Client Location';
    uploadImage='Upload Image';
    yourProblem='Your Problem';
    yourNote='Your Note';
     Appointment='Appointment';
    ClientNotes='Add Client Notes';
    empEvaluation ='Employee Evaluation';
    rate ='Your Rate';
    empName ='Officer Name ';
    sendNote ='send Note ';
    AdminNotes='Admin Notes';
    WriteYourNotes='Write Your Notes';
    noteLogin='You are not logged in';
    LoginCommented='Please login to be able to comment';

    ChangeUserName='Change User Name';
    ChangePhoneNumber='Change Phone Number';
    ChangeLocation='Change Your Location';
    Cancel='Cancel';
    Change='Change';
    OldPassword='Old Password';
    NewPassword ='New Password';
    ConfirmNewPassword ='Confirm New Password';
    notificationOffS ='You\'ve disabled the notifications';
    NotificationON ='Notification ON';
    NotificationOff ='Notification Off';
    changeDataSuccess ='The data has been modified successfully';
    changeImageSuccess ='The Image has been modified successfully';
    ok='ok';
    alerterror='Attention';
    alertWrongChange='It is not modified password. Please be sure to write a new password';
    Passwordliss6='Password less than 6 characters';
    filterBy='Filter By';
    complete='Finished';
    workingOn='Working On';
    cancel='Canceled';
    status='Status';
    problem='Problem';
    Products='Products';
    Product='Product Information';
    checkYourEmail='Check Your Email';
    sendPassword='We have sent a message containing the password to your email';
    sendProduct='Your order has been sent successfully';
    sendProductinfo='We will contact with you to determine the date of receipt of the order';
    alertDoneChange = 'Password changed successfully';
    selectProduct='Choose the quantity';
    SearchByDate='Search By Date';
    EmployeePage='Employee Window';
    ClientWindow='Client Window';
    sendNoteSuccessfully='Feedback has been sent successfully';
    menu='MENU';
    viewServices='view Services';
    details='details';
    NoServices='NoServices';
    blogs='blogs';
    Changelanguage='Change language';
    terms='terms and Condition ';
    Comments='Comments ';
    LeaveComment='Leave Comment ';
    EnteryourName='Enter your Name';
    EnteryourEmail='Enter your Email';
    writComment='writ Comment';
    note='note';
    Success='Success, Thank you';
    NoComment='No Comment';
    Welcometo='Welcome to';
    IndestryType='IndestryType';
    PrivacyPolicy='Privacy Policy';
    CommentedSuccessfully='Commented Successfully';
    Waitingadminapproval='Waiting for admin approval';
    enterFullName='Enter Full Name';
    pleaseEnterRealName='Please Enter Real Name';
    enterValedEmail='Enter Valid Email';
    ChooseLocation='Choose your location on map';
    Settings='Settings';
    companyName='company Name';
    Instegram='Instegram url';
    Twitter='Twitter url';
    wrongEmailOrPassword = 'The e-mail or password is incorrect!';

  }

}
class ArabicString extends Strings {
  ArabicString() {
    pleaseEnterRealName='الرجاء إدخال إسم حقيقي';
    pleaseFilltheData='يرجى ملء البيانات';
    pleaseEnterYourEmail='الرجاء إدخال البريد الالكتروني';
    enterValedEmail='الرجاء إدخال بريد الكاتروني صالح';
    noteLogin='لم تقم بتسجيل الدخول';
    LoginCommented='الرجاء تسجيل الدخول لتتمكن من التعليق';

    enterYourEmail='أدخل بريدك الإلكتروني';
    enterYourEmail='أدخل بريدك الإلكتروني';
    langPage = 'اللغة ';
    arabicLang = 'العربية';
    Twitter = 'رابط التويتر';
    englishLang = 'English';
    languages = 'English';
    languagesDes = 'اللغة';
    subscribeService = 'الاشتراك بالخدمات ';
    alertExitTitle='تنبيه الخروج';
    exitApp = 'هل تريد الخروج من التطبيق';
    home = 'الرئيسية';
    pleaseEnterYourName='الرجاء إدخال الإسم';
    profile = 'الملف الشخصي';
    share = 'مشاركة التطبيق';
    product = 'منتجات';
    Facebook = 'رابط الفيسبوك';
    Note = 'ملاحظة';
    assoon = 'سيتم التواصل معك في اقرب وقت ';
    loginGist = 'الدخول كزائر';
    Instegram = 'رباط الإنستجرام';
    ourclients = 'عملاؤنا';
    partner = 'العملاء';
    Submittedsuccessfully = 'تم التقديم بنجاح ';
    companyName = 'اسم الشركة ';
    Address = 'العملاء';
    IndestryType = 'نوع الصناعة';
    SnapChat = 'رابط السنابشات';
    services = 'الخدمات';
    ClientAccountcreated='تم انشاء حسابك بنجاح قم بتسجيل الدخول';
    sendPassword='لقد تم ارسال كلمة السر الى البريد الالكتروني الرجاء التاكد ';
    serviceNoti = 'الخدمة:';
    selectServices = 'حدد الخدمات';
    servicesDetails = 'تفاصيل الخدمة';
    contract = 'اتفافية';
    notification = 'الإشعارات';
    news = 'الأخبار';
    municipalCouncils = 'مجالس البلدية';
    theMedia = 'وسائل الاعلام';
    about = 'من نحن';
    contactUs = 'تواصل معنا';
    FAQ = 'الأسئلة الأكثر تكرار';
    complaintsAndSuggestions = 'شكاوي وإقتراحات';
     logout = 'تسجيل خروج';
    offers = 'العروض';
    login='تسجيل الدخول';
    userName='إسم المستخدم';
    fillDataError = 'يرجى إدخال المعلومات المطلوبة';
    errorUserName='يرجى إدخال إسم المستخدم';
    userPassword = 'كلمة السر';
    errorPassword = 'يرجى إدخال كلمة السر';
    signIn = 'تسجيل الدخول';
    signInWithFacebook = 'الدخول باستخدام الفيسبوك';
    dontHaveAccount = 'لا يوجد لديك حساب ؟';
    register = 'إنشاء حساب';
    alreadyHaveAccount = 'هل لديك حساب ؟';
    signUp = 'إنشاء حساب';
    firstUserName = 'الإسم الأول';
    lastUserName = 'الإسم الأخير';
    phoneNum = 'رقم الهاتف';
    email = 'البريد الإلكتروني';
    userRePassword = 'تأكيد كلمة السر';
    forgetPassword = ' هل نسيت كلمة السر ؟';
    passwordLess6='يجب ان يكون اكثر من 6 احرف';
    errorMatchPassword = 'يجب تطابق كلمتي السر !';
    errorPhone = 'يرجى إدخال رقم الهاتف ';
    phoneNumValid='يجب ان يكون رقم الجوال صحيح';
    send='إرسال';
    alertLogout='تنبيه تسجيل الخروج ';
    exitapp = 'هل تريد الخروج من التطبيق';
    emailUsed = 'البريد الإلكتروني مستخدم بالفعل';
    FirstName = 'الاسم الاول ';
    userEmail = 'البريد الإلكتروني ';
    welcome = 'مرحبا بكم في الهدهد ';
    yourMsg = 'رسالتك ';
    title = 'العنوان ';
    ComplaintTitle='إذا كان لديك أي اقتراح أو شكاوى ، فأخبرنا بذلك. ';
    addAppointment='أضف موعد';
    location='موقعك ';
    EmailInvalid='البريد الالكتروني غير فعال ';
    locationClient='موقع العميل';
    uploadImage='  تحميل صورة ';
    yourProblem='مشكلتك ! ';
    yourNote='ملاحظتك ';
    Appointment='المواعيد';
    ClientNotes='إضافة ملاحظات العميل ';
    empEvaluation='تقييم الموظف';
    rate=' تقييمك';
    empName=' اسم الموظف ';
    sendNote=' إرسال ملاحظة ';
    enterpassword='الرجاء إدخال كلمة المرور';
    AdminNotes='ملاحظات الادمن ';
    WriteYourNotes=' أكتب ملاحظاتك ';
    Contract='نوع العقد ';
    Landscaping='تنسيق حدائق ';
    Cost='التكلفة';
    Warranty='الضمان';
    Traps='عفش';
    Report='التقارير';
    Location='الموقع';
    ReceiptVoucher='سند القبض';
    Invoice='فاتورة';
    OfficerNotes='ملاحظات الموظف';
    WriteNotes='أكتب ملاحظاتك';
    SendNotes='ارسال الملاحظات';
    Profile='الملف الشخصي';
    Settings='الإعدادات';
    EditProfile='تعديل الملف الشخصي';
    ChangePassword='تعديل كلمة السر ';
    Notification='الإشعارات';
    Language='تعديل اللغة';
    ChangeUserName='تعديل إسم المستخدم';
    ChangePhoneNumber='تعديل رقم الجوال ';
    ChangeLocation='تعديل موقعك  ';
    Cancel='إلغاء';
    Change='تعديل';
    OldPassword='كلمة المرور القديمة';
    NewPassword='كلمة المرور الجديدة';
    ConfirmNewPassword='تأكيد كلمة المرور';
    ConfirmNewPassword='تأكيد كلمة المرور';
    notificationOffS='لقد قمت بتعطيل الإشعارات';
    NotificationON='تفعيل الإشعارات';
    NotificationOff='تعطيل الإشعارات';
    changeDataSuccess='تم تعديل البيانات بنجاح';
    changeImageSuccess='تم تعديل الصورة الشخصية بنجاح';
    ok='موافق';
    alerterror='تنبيه' ;
    alertWrongChange='لم يتم تعديل كلمة المرور. الرجاء التأكد من كتابة كلمة مرور جديدة' ;
    Passwordliss6='كلمة المرور أقل من 6 احرف';
    filterBy='تصفية حسب';
    complete='تم انهاء العمل';
    workingOn='جاري العمل عليه ';
    cancel='ألغيت';
    status='الحالة';
    problem='المشكلة';
    Products='المنتجات';
    Product='معلومات المنتج';
    ExchangePoint='التبديل بالنقاط';
    points='النقاط';
    JD='د.ا';
    ProductPrice='سعر المنتج';
    ReadMore='اقرأ أكثر';
    Quantity='الكمية';
    terms = 'الشروط و الأحكام';
    sendDone = 'تم الإرسال بنجاح';
    wrongEmailOrPassword = 'البريد الالكتروني او كلمة السر غير صحيحة !';
    accNotActive = 'حسابك غير فعال';
    forgotYourPassword='هل نسيت كلمة السر؟';
    PleaseCheckPassword='الرجاء التحقق من كلمة المرور';

    menu='القائمة';
    viewServices='إظهار الخدمات';
    details='التفاصيل';
    NoServices='لا يوجد خدمة';
    blogs='المدونات';
    Changelanguage='تغيير اللغة';
    Comments='التعليقات';
    LeaveComment='أضف تعليق';
    EnteryourName='أدخل إسمك';
    EnteryourEmail='أدخل البريد الالكتروني';
    writComment='أكتب تعليقك';
    PleaseWait='الرجاء الانتظار ';
    no='لا';
    yes='نعم';
    note='تنويه';
    Success='تم بنجاح، شكرا';
    NoComment='لا يوجد تعليقات';
    Welcometo ='مرحبا بك في';
    PrivacyPolicy ='سياسة الخصوصية';
    CommentedSuccessfully ='تم التعليق بنجاح ';
    Waitingadminapproval ='في انتظار موافقة المسؤول';
    enterFullName='أدخل الاسم الكامل';
    createANewAccount='انشاء حساب جديد ؟';
    registration='إنشاء حساب';
    ChooseLocation=' إختر الموقع على الخارطة';
    ChooseyourLocation='إختر موقعك';
    ForgotPassword = 'أكتب البريدالإلكتروني وسنرسل لك كلمة المرور ';
    FillEmail = 'الرجاء كتابة البريد الالكتروني';

  }
}
